// Terpene profile data for Polish medical cannabis strains
// Terpene values represent relative proportions (0-10 scale) based on budcare.pl profiles

export const TERPENES_LIST = [
  "mircen", "limonen", "kariofilen", "terpinolen", "pinen",
  "linalol", "humulen", "ocymen", "bisabolol", "nerolidol",
  "guaiol", "farnezen", "selinadien"
];

export const STRAINS = [
  {
    id: "snowtorious-krypton",
    name: "Snowtorious Krypton",
    producer: "Spectrum Therapeutics (Canopy Growth)",
    genetics: "Indica",
    thc: 25,
    cbd: 0.5,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Diesel", "Piżmowy", "Ziemisty"],
    description: "Indica o ciężkim, wyrazistym charakterze, powstała z połączenia genetyki Kryptona i Kush Mints. Intensywnie zielone kwiaty pokryte grubą warstwą trichomów.",
    terpenes: { mircen: 8, limonen: 5, kariofilen: 4, linalol: 2, pinen: 1, humulen: 2, ocymen: 1 },
    dominantTerpene: "Mircen",
    packaging: "5g"
  },
  {
    id: "blood-orange-kush",
    name: "Blood Orange Kush",
    producer: "Spectrum Therapeutics (Canopy Growth)",
    genetics: "Indica",
    thc: 29,
    cbd: 0.5,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Cytrusowy", "Korzenny", "Ziemisty"],
    description: "Odmiana z przewagą genetyki indica, z połączenia Lemon Kush oraz Guava Kush. Charakteryzuje się wysoką zawartością THC i wyraźnym cytrusowym profilem aromatycznym.",
    terpenes: { limonen: 7, mircen: 6, linalol: 4, kariofilen: 3, humulen: 1, pinen: 1 },
    dominantTerpene: "Limonen",
    packaging: "5g, 15g"
  },
  {
    id: "kush-mints",
    name: "Kush Mints",
    producer: "Spectrum Therapeutics (Canopy Growth)",
    genetics: "Hybryda",
    thc: 28,
    cbd: 0.5,
    availability: "Wysoka",
    effect: "Zrównoważone",
    aromas: ["Miętowy", "Sosnowy", "Ziemisty", "Ziołowy"],
    description: "Hybryda 50/50 indica/sativa, z połączenia Bubba Kush i Animal Mints. Gęste, żywiczne pąki w odcieniach intensywnej zieleni z fioletowymi refleksami.",
    terpenes: { selinadien: 6, kariofilen: 5, mircen: 4, pinen: 3, humulen: 3, limonen: 2, linalol: 1 },
    dominantTerpene: "Selinadien",
    packaging: "5g"
  },
  {
    id: "bakerstreet",
    name: "Bakerstreet",
    producer: "Spectrum Therapeutics (Canopy Growth)",
    genetics: "Indica",
    thc: 20,
    cbd: 0.5,
    availability: "Brak",
    effect: "Relaksujące",
    aromas: ["Kamfora", "Lawendowy", "Mango", "Miętowy", "Pieprzowy"],
    description: "Odmiana o przewadze indica, mocno relaksujący efekt na ciele. Mircen daje ziołowy aromat, terpinolen nutę cytrusowo-drzewną.",
    terpenes: { mircen: 7, terpinolen: 5, ocymen: 4, pinen: 3, kariofilen: 2, linalol: 1 },
    dominantTerpene: "Mircen",
    packaging: "5g"
  },
  {
    id: "red-velvet-cake",
    name: "Red Velvet Cake",
    producer: "Spectrum Therapeutics (Canopy Growth)",
    genetics: "Sativa",
    thc: 27,
    cbd: 0.5,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Pikantny", "Słodki", "Waniliowy"],
    description: "Sativa o intensywnym profilu aromatycznym, ze skrzyżowania Red Headed Stranger × Cookies N' Cream. Słodkie nuty wanilii, śmietanki i orzechów.",
    terpenes: { limonen: 6, mircen: 5, kariofilen: 5, linalol: 2, humulen: 2, pinen: 1 },
    dominantTerpene: "Limonen",
    packaging: "5g"
  },
  {
    id: "jack-haze",
    name: "Jack Haze",
    producer: "Spectrum Therapeutics (7ACRES)",
    genetics: "Sativa",
    thc: 19,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Kamfora", "Sosnowy"],
    description: "Sativa-dominująca odmiana będąca krzyżówką White Widow i Haze. Pobudzająca myśli i kreatywność, działająca energetyzująco.",
    terpenes: { terpinolen: 7, mircen: 5, ocymen: 4, pinen: 3, limonen: 2, kariofilen: 1 },
    dominantTerpene: "Terpinolen",
    packaging: "5g"
  },
  {
    id: "delahaze",
    name: "Delahaze",
    producer: "Aurora Deutschland GmbH",
    genetics: "Sativa",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Korzenny", "Miętowy", "Pieprzowy", "Sosnowy", "Ziołowy"],
    description: "Krzyżowanie odmian Mango i Lemon Skunk. Owocowy aromat z nutami sosnowymi. Działanie aktywizujące i stymulujące.",
    terpenes: { terpinolen: 7, mircen: 5, pinen: 3, kariofilen: 2, ocymen: 2, limonen: 2, linalol: 1 },
    dominantTerpene: "Terpinolen",
    packaging: "10g"
  },
  {
    id: "pink-kush-aurora-20",
    name: "Pink Kush (Aurora 20%)",
    producer: "Aurora Deutschland GmbH",
    genetics: "Indica",
    thc: 20,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Drzewny", "Pieprzowy", "Pikantny", "Różany"],
    description: "Indica o klasycznym kushowym charakterze, z połączenia OG Kush i Hindu Kush. Silne działanie przeciwbólowe, zwalczające migreny i nudności.",
    terpenes: { mircen: 8, kariofilen: 5, linalol: 3, limonen: 2, humulen: 2, pinen: 1, bisabolol: 1 },
    dominantTerpene: "Mircen",
    packaging: "10g"
  },
  {
    id: "ghost-train-haze",
    name: "Ghost Train Haze",
    producer: "Aurora Deutschland GmbH",
    genetics: "Sativa",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Korzenny", "Kwaśny", "Pikantny", "Sosnowy"],
    description: "Bardzo mocna odmiana sativa. Efekty bywają uważane za graniczne z psychodelicznymi. Wysoka zawartość terpinolenu i limonenu.",
    terpenes: { terpinolen: 8, limonen: 5, mircen: 3, linalol: 3, pinen: 2, kariofilen: 1, ocymen: 1 },
    dominantTerpene: "Terpinolen",
    packaging: "10g"
  },
  {
    id: "aurora-electric-honeydew",
    name: "Electric Honeydew",
    producer: "Aurora Deutschland GmbH",
    genetics: "Sativa",
    thc: 29,
    cbd: 0.5,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Owocowy", "Paliwowy", "Sosnowy"],
    description: "Sativa oparta na genetyce Girl Scout Cookies × 91 OG Krypt Melon. Wysoka zawartość THC, gęste ciemnozielone kwiaty z pomarańczowymi słupkami. Nuty melona, gazu i sosny.",
    terpenes: { mircen: 8, limonen: 7, kariofilen: 4, nerolidol: 3, linalol: 2, pinen: 1 },
    dominantTerpene: "Mircen",
    packaging: "10g"
  },
  {
    id: "aurora-27-black-jelly",
    name: "Black Jelly",
    producer: "Aurora Deutschland GmbH",
    genetics: "Sativa",
    thc: 27,
    cbd: 0.5,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Owocowy", "Słodki"],
    description: "Hybryda o dominującym typie sativa, z linii Alien Cake 3030 × MAC (Miracle Alien Cookies). Profil terpenowy o wyraźnej nucie słodkiej czarnej lukrecji z owocowym tłem.",
    terpenes: { limonen: 7, mircen: 6, kariofilen: 5, linalol: 2, pinen: 1 },
    dominantTerpene: "Limonen",
    packaging: "10g"
  },
  {
    id: "equiposa",
    name: "Equiposa",
    producer: "Aurora Deutschland GmbH",
    genetics: "Hybryda/Sativa",
    thc: 8,
    cbd: 8.0,
    availability: "Wycofana",
    effect: "Zrównoważone",
    aromas: ["Miętowy", "Pieprzowy", "Sosnowy", "Ziemisty"],
    description: "Hybryda o zbalansowanym THC:CBD. Relaksujące efekty z zachowaniem jasności umysłu. Profil terpenów mircen-pinen.",
    terpenes: { mircen: 6, pinen: 5, kariofilen: 3, limonen: 2, linalol: 2, terpinolen: 1, humulen: 1 },
    dominantTerpene: "Mircen",
    packaging: "10g"
  },
  {
    id: "s-lab-22-animintz",
    name: "Animintz",
    producer: "S-Lab",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Ziemisty", "Cytrusowy", "Kwiatowy"],
    description: "Hybryda z dominacją indica (70/30), z połączenia Animal Mintz oraz Purp Skurp. Aromat łączy nuty ziemiste, cytrusowe i kwiatowe.",
    terpenes: { linalol: 7, kariofilen: 6, mircen: 5, limonen: 4, humulen: 2, bisabolol: 1 },
    dominantTerpene: "Linalol",
    packaging: "10g"
  },
  {
    id: "s-lab-22-pink-certz",
    name: "Pink Certz 22",
    producer: "S-Lab",
    genetics: "Hybryda/Sativa",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Mentolowy", "Diesel", "Chemiczny"],
    description: "Hybryda z dominacją sativa (80/20) z połączenia The Menthol oraz Grape Gasoline. Profil terpenowy z dominacją nerolidolu, limonenu i kariofilenu.",
    terpenes: { nerolidol: 7, limonen: 5, kariofilen: 5, mircen: 2, humulen: 2, linalol: 1 },
    dominantTerpene: "Nerolidol",
    packaging: "10g"
  },
  {
    id: "s-lab-18-pink-certz",
    name: "Pink Certz 18",
    producer: "S-Lab",
    genetics: "Hybryda/Sativa",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Mentolowy", "Diesel", "Chemiczny"],
    description: "Wersja 18% THC odmiany Pink Certz. Hybryda z dominacją sativa (80/20). Dominacja nerolidolu, limonenu i kariofilenu.",
    terpenes: { nerolidol: 7, limonen: 5, kariofilen: 5, mircen: 2, humulen: 2, linalol: 1 },
    dominantTerpene: "Nerolidol",
    packaging: "15g"
  },
  {
    id: "s-lab-18-animal-rntz",
    name: "Animal Rntz",
    producer: "S-Lab",
    genetics: "Hybryda/Indica",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Owocowy", "Słodko-kwaśny", "Ziemisty"],
    description: "Hybryda z dominacją indica (60/40) ze skrzyżowania Animal Cookies oraz Runtz. Dominują kariofilen, limonen oraz linalol.",
    terpenes: { kariofilen: 7, limonen: 5, linalol: 5, mircen: 3, humulen: 2, farnezen: 1 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "s-lab-18-spiced-latte",
    name: "Spiced Latte",
    producer: "S-Lab",
    genetics: "Hybryda/Sativa",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Korzenny", "Ziołowy", "Cytrusowy"],
    description: "Hybryda z przewagą sativa (80/20), ze skrzyżowania Jean Guy i Alien Dawg. Pobudzający profil z nutami korzenno-ziołowymi.",
    terpenes: { terpinolen: 6, mircen: 4, kariofilen: 3, limonen: 3, pinen: 2, ocymen: 2 },
    dominantTerpene: "Terpinolen",
    packaging: "15g"
  },
  {
    id: "s-lab-22-pink-kush",
    name: "Pink Kush (S-Lab 22%)",
    producer: "S-Lab",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Drzewny", "Pikantny", "Różany", "Ziemisty"],
    description: "Odmiana powstała z połączenia OG Kush i Hindu Kush. Znana jako skuteczny środek przeciwbólowy i przeciwlękowy. Działa korzystnie w przypadku zaburzeń snu.",
    terpenes: { mircen: 8, kariofilen: 5, linalol: 3, limonen: 2, humulen: 2, pinen: 1, bisabolol: 1 },
    dominantTerpene: "Mircen",
    packaging: "15g"
  },
  {
    id: "s-lab-22-galaxy-walker-og",
    name: "Galaxy Walker OG (S-Lab 22%)",
    producer: "S-Lab",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Korzenny", "Miętowy", "Pikantny", "Sosnowy"],
    description: "Hybryda z dominacją indica o niezwykle bogatym profilu terpenowym. Silna obecność nerolidolu i kariofilenu przekłada się na właściwości przeciwbólowe i przeciwzapalne.",
    terpenes: { nerolidol: 7, kariofilen: 6, limonen: 4, linalol: 3, mircen: 2, pinen: 1 },
    dominantTerpene: "Nerolidol",
    packaging: "15g"
  },
  {
    id: "s-lab-22-powdered-donuts",
    name: "Powdered Donuts",
    producer: "S-Lab",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Cytrusowy", "Słodki", "Waniliowy", "Ziołowy"],
    description: "Hybryda z dominacją indica (60/40), z genetyki Jet Fuel Gelato × Orange Cookies. Słodki, ziołowo-cytrusowy aromat z nutą wanilii. Głębokie odprężenie z poprawą nastroju.",
    terpenes: { kariofilen: 6, mircen: 5, limonen: 5, linalol: 3, humulen: 1 },
    dominantTerpene: "Kariofilen",
    packaging: "10g"
  },
  {
    id: "s-lab-22-wappa",
    name: "Wappa (S-Lab 22%)",
    producer: "S-Lab",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Drzewny", "Owocowy", "Słodki"],
    description: "Hybryda z dominacją indica (60/40), z genetyki Skunka. Słodko-drzewny aromat z nutami owoców. Wieczorne, relaksujące działanie.",
    terpenes: { kariofilen: 6, mircen: 5, pinen: 4, humulen: 3, linalol: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "s-lab-22-inzane",
    name: "Inzane in the Membrane",
    producer: "S-Lab",
    genetics: "Hybryda/Sativa",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Sosnowy", "Ziołowy"],
    description: "Energetyczna hybryda o dominujących cechach sativy. Działanie wyraźnie pobudzające z wpływem na motorykę i napięcie mięśniowe. Złożony profil terpenowy z przewagą kariofilenu i terpinolenu.",
    terpenes: { kariofilen: 7, terpinolen: 5, humulen: 4, ocymen: 3, limonen: 2, pinen: 1 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "s-lab-18-lilac-diesel",
    name: "Lilac Diesel (S-Lab 18%)",
    producer: "S-Lab",
    genetics: "Hybryda/Sativa",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Diesel", "Kwiatowy", "Lawendowy"],
    description: "Odmiana opisywana jako 'dodająca energii i otuchy'. Uczucie lekkości, lepszy nastrój i redukcja stresu. Kariofilen i linalol odpowiadają za właściwości kojące.",
    terpenes: { kariofilen: 6, linalol: 5, limonen: 4, mircen: 3, pinen: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "s-lab-beach-crasher-18",
    name: "Beach Crasher 18%",
    producer: "S-Lab (Tilray)",
    genetics: "Hybryda/Indica",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Ziemisty", "Cytrusowy", "Korzenny"],
    description: "Hybryda z przewagą indica. Ziemisto-cytrusowy aromat z korzennym tłem. Dominujące kariofilen, humulen, nerolidol i mircen.",
    terpenes: { kariofilen: 6, humulen: 5, nerolidol: 4, mircen: 4, limonen: 2, pinen: 1 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "s-lab-beach-crasher-22",
    name: "Beach Crasher 22%",
    producer: "S-Lab (Tilray)",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Ziemisty", "Cytrusowy", "Korzenny"],
    description: "Wersja 22% odmiany Beach Crasher. Hybryda z przewagą indica o łagodnym, relaksującym charakterze.",
    terpenes: { kariofilen: 6, humulen: 5, nerolidol: 4, mircen: 4, limonen: 2, pinen: 1 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "cosma-22-black-r",
    name: "Black R",
    producer: "Cosma",
    genetics: "Hybryda",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Korzenny", "Ziemisty", "Drzewny"],
    description: "Hybryda 50/50 indica-sativa o fenotypie Black Russian, oparta na genetyce Black Domina x White Russian. Klasyczny, wytrawny charakter.",
    terpenes: { kariofilen: 8, humulen: 6, mircen: 4, limonen: 3, linalol: 1, pinen: 1 },
    dominantTerpene: "Kariofilen",
    packaging: "10g"
  },
  {
    id: "tilray-18-cataract-kush",
    name: "Cataract Kush (Tilray 18%)",
    producer: "Tilray",
    genetics: "Indica",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Owocowy", "Ziołowy", "Pikantny", "Ziemisty", "Drzewny"],
    description: "Indica o klasycznym kushowym charakterze, z połączenia LA Confidential i OG Kush. Gęste kwiaty z umiarkowaną ilością trichomów.",
    terpenes: { mircen: 6, kariofilen: 5, humulen: 4, limonen: 3, linalol: 2, pinen: 2 },
    dominantTerpene: "Mircen",
    packaging: "10g"
  },
  {
    id: "tilray-22-cataract-kush",
    name: "Cataract Kush (Tilray 22%)",
    producer: "Tilray",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Owocowy", "Ziołowy", "Pikantny", "Ziemisty", "Drzewny"],
    description: "Wersja 22% THC odmiany Cataract Kush od Tilray. Indica z połączenia LA Confidential i OG Kush.",
    terpenes: { mircen: 6, kariofilen: 5, humulen: 4, limonen: 3, linalol: 2, pinen: 2 },
    dominantTerpene: "Mircen",
    packaging: "15g"
  },
  {
    id: "tilray-22-lilac-diesel",
    name: "Lilac Diesel (Tilray 22%)",
    producer: "Tilray",
    genetics: "Hybryda/Sativa",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Diesel", "Kwiatowy", "Lawendowy"],
    description: "Odmiana opisywana jako 'dodająca energii i otuchy'. Uczucie lekkości, lepszy nastrój, mniejsze przytłoczenie codziennością. Kariofilen i linalol nadają właściwości kojące.",
    terpenes: { kariofilen: 6, linalol: 5, limonen: 4, mircen: 3, pinen: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "tilray-18-lilac-diesel",
    name: "Lilac Diesel (Tilray 18%)",
    producer: "Tilray",
    genetics: "Hybryda/Sativa",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Diesel", "Kwiatowy", "Lawendowy"],
    description: "Wersja 18% odmiany Lilac Diesel. Odmiana 'dodająca energii i otuchy', szczególnie polecana przy przewlekłym stresie.",
    terpenes: { kariofilen: 6, linalol: 5, limonen: 4, mircen: 3, pinen: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "tilray-22-master-kush",
    name: "Master Kush (Tilray 22%)",
    producer: "Tilray",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Kamfora", "Korzenny", "Pieprzowy", "Ziemisty"],
    description: "Odmiana tetraploidalna o przewadze genetyki indica. Silna euforia, wspomaganie snu i łagodzenie bólu. Idealna do wieczornego relaksu.",
    terpenes: { kariofilen: 6, mircen: 4, pinen: 3, humulen: 3, linalol: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "tilray-22-pink-kush",
    name: "Pink Kush (Tilray 22%)",
    producer: "Tilray",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Drzewny", "Pikantny", "Różany", "Ziemisty"],
    description: "Odmiana z połączenia OG Kush i Hindu Kush od Tilray. Skuteczny środek przeciwbólowy i przeciwlękowy, wspomaga sen.",
    terpenes: { mircen: 8, kariofilen: 5, linalol: 3, limonen: 2, humulen: 2, pinen: 1, bisabolol: 1 },
    dominantTerpene: "Mircen",
    packaging: "15g"
  },
  {
    id: "synoptis-18-cataract-kush",
    name: "Cataract Kush (Synoptis 18%)",
    producer: "Synoptis Pharma",
    genetics: "Indica",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Owocowy", "Ziołowy", "Pikantny", "Ziemisty", "Drzewny"],
    description: "Indica o klasycznym kushowym charakterze, z połączenia LA Confidential i OG Kush. Dystrybucja Synoptis Pharma.",
    terpenes: { mircen: 6, kariofilen: 5, humulen: 4, limonen: 3, linalol: 2, pinen: 2 },
    dominantTerpene: "Mircen",
    packaging: "10g"
  },
  {
    id: "synoptis-22-purps",
    name: "Purps (Synoptis 22%)",
    producer: "Synoptis Pharma",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Ziemisty", "Kwiatowy", "Pikantny"],
    description: "Hybryda z przewagą indica (70%). Głębokie, uspokajające działanie. Kariofilen, bisabolol i linalol w profilu terpenowym.",
    terpenes: { kariofilen: 6, bisabolol: 5, linalol: 5, mircen: 3, limonen: 2, humulen: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "10g"
  },
  {
    id: "synoptis-22-master-kush",
    name: "Master Kush (Synoptis 22%)",
    producer: "Synoptis Pharma",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Kamfora", "Korzenny", "Pieprzowy", "Ziemisty"],
    description: "Odmiana tetraploidalna o przewadze genetyki indica. Silna euforia, wspomaganie snu i łagodzenie bólu. Idealna do wieczornego relaksu.",
    terpenes: { kariofilen: 6, mircen: 4, pinen: 3, humulen: 3, linalol: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "synoptis-22-facade",
    name: "Facade",
    producer: "Synoptis Pharma",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Zrównoważone",
    aromas: ["Cytrusowy", "Owocowy", "Pieprzowy", "Sosnowy", "Ziołowy"],
    description: "Hybryda ze skrzyżowania Eye Candy × Apples & Bananas. Zbalansowane działanie — zaczyna od uniesienia nastroju i koncentracji, przechodzi w relaks. Limonen i kariofilen w profilu.",
    terpenes: { limonen: 6, kariofilen: 6, mircen: 4, linalol: 3, pinen: 2, humulen: 1 },
    dominantTerpene: "Limonen",
    packaging: "15g"
  },
  {
    id: "synoptis-22-galaxy-walker-og",
    name: "Galaxy Walker OG (Synoptis 22%)",
    producer: "Synoptis Pharma",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Korzenny", "Miętowy", "Pikantny", "Sosnowy"],
    description: "Hybryda z dominacją indica o bogatym profilu terpenowym. Nerolidol i kariofilen przekładają się na działanie przeciwbólowe i przeciwzapalne.",
    terpenes: { nerolidol: 7, kariofilen: 6, limonen: 4, linalol: 3, mircen: 2, pinen: 1 },
    dominantTerpene: "Nerolidol",
    packaging: "15g"
  },
  {
    id: "synoptis-22-pink-kush",
    name: "Pink Kush (Synoptis 22%)",
    producer: "Synoptis Pharma",
    genetics: "Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Drzewny", "Pikantny", "Różany", "Ziemisty"],
    description: "Odmiana z połączenia OG Kush i Hindu Kush od Synoptis. Skuteczny środek przeciwbólowy i przeciwlękowy, wspomaga sen.",
    terpenes: { mircen: 8, kariofilen: 5, linalol: 3, limonen: 2, humulen: 2, pinen: 1, bisabolol: 1 },
    dominantTerpene: "Mircen",
    packaging: "15g"
  },
  {
    id: "synoptis-22-lilac-diesel",
    name: "Lilac Diesel (Synoptis 22%)",
    producer: "Synoptis Pharma",
    genetics: "Hybryda/Sativa",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Diesel", "Kwiatowy", "Lawendowy"],
    description: "Odmiana 'dodająca energii i otuchy'. Uczucie lekkości, lepszy nastrój i redukcja stresu. Wersja 22% od Synoptis Pharma.",
    terpenes: { kariofilen: 6, linalol: 5, limonen: 4, mircen: 3, pinen: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "synoptis-18-lilac-diesel",
    name: "Lilac Diesel (Synoptis 18%)",
    producer: "Synoptis Pharma",
    genetics: "Hybryda/Sativa",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Diesel", "Kwiatowy", "Lawendowy"],
    description: "Wersja 18% odmiany Lilac Diesel od Synoptis Pharma. Pobudzający profil z właściwościami kojącymi.",
    terpenes: { kariofilen: 6, linalol: 5, limonen: 4, mircen: 3, pinen: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "synoptis-22-wappa",
    name: "Wappa (Synoptis 22%)",
    producer: "Synoptis Pharma",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Brak",
    effect: "Relaksujące",
    aromas: ["Drzewny", "Owocowy", "Skunk", "Słodki"],
    description: "Hybryda z dominacją indica (60/40) z genetyki Skunka. Słodko-drzewny aromat. Sprzyja relaksowi, senności i poprawie nastroju.",
    terpenes: { kariofilen: 6, mircen: 5, pinen: 4, humulen: 3, linalol: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "15g"
  },
  {
    id: "synoptis-18-frosted-cherry-cookies",
    name: "Frosted Cherry Cookies",
    producer: "Synoptis Pharma",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Jagodowy", "Cytrusowy", "Słodki", "Żywiczny"],
    description: "Hybryda z dominacją indica (70/30) o intensywnym aromacie i kompleksowym profilu terpenowym. Aromat jagód, cytrusów i żywicy. Wyciszające działanie wieczorne.",
    terpenes: { linalol: 6, kariofilen: 5, mircen: 4, limonen: 4, bisabolol: 2, humulen: 1 },
    dominantTerpene: "Linalol",
    packaging: "15g"
  },
  {
    id: "synoptis-18-pink-kush",
    name: "Pink Kush (Synoptis 18%)",
    producer: "Synoptis Pharma",
    genetics: "Indica",
    thc: 18,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Drzewny", "Pikantny", "Różany", "Ziemisty"],
    description: "Wersja 18% odmiany Pink Kush od Synoptis Pharma. Z połączenia OG Kush i Hindu Kush, skuteczna przy bólu i bezsennicy.",
    terpenes: { mircen: 8, kariofilen: 5, linalol: 3, limonen: 2, humulen: 2, pinen: 1, bisabolol: 1 },
    dominantTerpene: "Mircen",
    packaging: "15g"
  },
  {
    id: "synoptis-22-island-sweet-skunk",
    name: "Island Sweet Skunk",
    producer: "Synoptis Pharma",
    genetics: "Sativa",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Owocowy", "Słodki", "Tropikalny"],
    description: "Energetyzująca odmiana typu sativa o tropikalnym aromacie. Kwiaty jasnozielone, cytrusowo-owocowy zapach z akcentami sosny. Dominuje pinen, kariofilen i terpinolen.",
    terpenes: { pinen: 6, kariofilen: 4, terpinolen: 4, limonen: 4, ocymen: 2, mircen: 2 },
    dominantTerpene: "Pinen",
    packaging: "15g"
  },
  {
    id: "cantourage-gelato-33",
    name: "Gelato 33",
    producer: "Cantourage",
    genetics: "Hybryda",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Zrównoważone",
    aromas: ["Cytrusowy", "Słodki", "Waniliowy"],
    description: "Hybryda 50/50 Indica/Sativa z krzyżówki Sunset Sherbert × Thin Mint Girl Scout Cookies, uprawiana przez LOT420 w Kanadzie. Słodko-kwaśny aromat cytrusów.",
    terpenes: { limonen: 7, kariofilen: 5, linalol: 4, mircen: 3, pinen: 2 },
    dominantTerpene: "Limonen",
    packaging: "10g"
  },
  {
    id: "suprobion-mystic-wonder",
    name: "Mystic Wonder",
    producer: "Suprobion",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Cytrusowy", "Drzewny", "Owocowy", "Ziemisty"],
    description: "Hybryda z dominacją indica (60/40). Profil aromatyczny z nutami cytrusowymi, ziemistymi, owocowymi i drzewnymi. Mircen, limonen i kariofilen w profilu terpenowym.",
    terpenes: { mircen: 7, limonen: 5, kariofilen: 4, linalol: 2, pinen: 1 },
    dominantTerpene: "Mircen",
    packaging: "10g"
  },
  {
    id: "suprobion-gorilla-glue",
    name: "Gorilla Glue",
    producer: "Suprobion",
    genetics: "Hybryda/Indica",
    thc: 23,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Diesel", "Sosnowy", "Ziemisty", "Żywiczny"],
    description: "Klasyczna hybryda z dominacją indici (65/35), o wysokiej zawartości THC. Intensywny relaks fizyczny. Ciężki, lepki aromat — nuty ziemiste, sosnowe, dieslowe. Kariofilen, mircen i limonen w profilu.",
    terpenes: { kariofilen: 7, mircen: 6, limonen: 4, humulen: 3, pinen: 2 },
    dominantTerpene: "Kariofilen",
    packaging: "10g"
  },
  {
    id: "suprobion-humble-warrior",
    name: "Humble Warrior",
    producer: "Suprobion",
    genetics: "Hybryda/Sativa",
    thc: 23,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Pobudzające",
    aromas: ["Cytrusowy", "Mentolowy", "Sosnowy"],
    description: "Hybryda z dominacją sativy (60/40) z rodowodu Alaska MTF. Wyraźnie pobudzający profil działania. Aromat z nutami sosny, cytrusów, skunka i mentolu.",
    terpenes: { pinen: 6, terpinolen: 5, limonen: 5, kariofilen: 3, ocymen: 2 },
    dominantTerpene: "Pinen",
    packaging: "10g"
  },
  {
    id: "phytopur-bio-frosted-lemon-angel",
    name: "Frosted Lemon Angel",
    producer: "Phytopur BIO",
    genetics: "Hybryda/Indica",
    thc: 24,
    cbd: 0.5,
    availability: "Wysoka",
    effect: "Relaksujące",
    aromas: ["Cytrusowy", "Kwiatowy", "Słodki"],
    description: "Hybryda z przewagą indica z rodowodu Lemon Skunk × Kosher Kush. Jasnozielone kwiaty z obfitą warstwą trichomów. Dostępna w opakowaniach 10g, sterylizowana beta-promieniowaniem.",
    terpenes: { limonen: 7, mircen: 5, linalol: 3, kariofilen: 2, pinen: 1 },
    dominantTerpene: "Limonen",
    packaging: "10g"
  },
  {
    id: "phytopur-bio-big-purple-dragon",
    name: "Big Purple Dragon",
    producer: "Phytopur BIO",
    genetics: "Hybryda/Indica",
    thc: 22,
    cbd: 1.0,
    availability: "Wysoka",
    effect: "Zrównoważone",
    aromas: ["Kwiatowy", "Owocowy", "Słodki"],
    description: "Odmiana oferująca połączenie fizycznego relaksu i klarowności umysłu. Terpeny mogą wykazywać działanie zarówno kojące, jak i ożywcze. Sprawdza się przy wzmacnianiu kreatywności i redukcji stresu.",
    terpenes: { linalol: 5, mircen: 5, kariofilen: 4, limonen: 4, bisabolol: 2 },
    dominantTerpene: "Linalol",
    packaging: "10g"
  }
];

// Calculate cosine similarity between two terpene profiles
export function cosineSimilarity(profile1, profile2) {
  let dotProduct = 0;
  let norm1 = 0;
  let norm2 = 0;

  for (const terpene of TERPENES_LIST) {
    const v1 = profile1[terpene] || 0;
    const v2 = profile2[terpene] || 0;
    dotProduct += v1 * v2;
    norm1 += v1 * v1;
    norm2 += v2 * v2;
  }

  if (norm1 === 0 || norm2 === 0) return 0;
  return dotProduct / (Math.sqrt(norm1) * Math.sqrt(norm2));
}

// Get similar strains sorted by terpene profile similarity
export function getSimilarStrains(strainId, count = 5) {
  const strain = STRAINS.find(s => s.id === strainId);
  if (!strain) return [];

  return STRAINS
    .filter(s => s.id !== strainId)
    .map(s => ({
      ...s,
      similarity: cosineSimilarity(strain.terpenes, s.terpenes)
    }))
    .sort((a, b) => b.similarity - a.similarity)
    .slice(0, count);
}